# Generated by Django 5.1.6 on 2025-10-19 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_bio_userprofile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(blank=True, default='profile_images/default_profile.png', null=True, upload_to='profile_images/'),
        ),
    ]
