# Generated by Django 5.1.6 on 2025-10-20 17:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='participants',
            field=models.ManyToManyField(related_name='participants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rsvp',
            name='event',
            field=models.ManyToManyField(blank=True, related_name='rsvps', to='events.event'),
        ),
        migrations.AddField(
            model_name='rsvp',
            name='lastEventRSVPed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.event'),
        ),
        migrations.AddField(
            model_name='rsvp',
            name='lastUserRSVPed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rsvp',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='rsvps', to=settings.AUTH_USER_MODEL),
        ),
    ]
