# Generated by Django 5.1.6 on 2025-05-29 15:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_remove_event_participants_event_participants'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RSVP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Timestamp', models.DateTimeField(auto_now_add=True)),
                ('event', models.ManyToManyField(blank=True, null=True, related_name='rsvp', to='events.event')),
                ('user', models.ManyToManyField(blank=True, null=True, related_name='rsvp', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
