# Generated by Django 5.1.6 on 2025-05-29 15:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_rsvp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='rsvp',
            name='event',
            field=models.ManyToManyField(blank=True, related_name='rsvp', to='events.event'),
        ),
        migrations.AlterField(
            model_name='rsvp',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='rsvp', to=settings.AUTH_USER_MODEL),
        ),
    ]
