# Generated by Django 5.1.6 on 2025-05-29 16:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_alter_rsvp_event_alter_rsvp_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='rsvp',
            name='event',
            field=models.ManyToManyField(blank=True, related_name='rsvps', to='events.event'),
        ),
        migrations.AlterField(
            model_name='rsvp',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='rsvps', to=settings.AUTH_USER_MODEL),
        ),
    ]
