# Generated by Django 5.1.6 on 2025-05-31 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_rsvp_lastuserrsvped'),
    ]

    operations = [
        migrations.AddField(
            model_name='rsvp',
            name='lastEventRSVPed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.event'),
        ),
    ]
