# Generated by Django 5.1.6 on 2025-08-03 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_rsvp_lasteventrsvped'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='thumbnail',
            field=models.ImageField(blank=True, default='default_thumbnail.jpg', null=True, upload_to='event_thumbnails/'),
        ),
    ]
