# Generated by Django 5.1.6 on 2025-08-03 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_event_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='thumbnail',
            field=models.ImageField(blank=True, default='event_thumbnails/default_thumbnail.jpg', null=True, upload_to='event_thumbnails/'),
        ),
    ]
